apiVersion: v1
kind: Service
metadata:
  name: helloworld-loadbalancer
spec:
  selector:
    app: user-service
  type: LoadBalancer
  ports:
    - name: tcphello
      port: 8085
      targetPort: 8090