apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    database: postgresql
  type: LoadBalancer
  ports:
    - port: 1122
      targetPort: 5432
      name: tcppostgre