apiVersion: v1
kind: Service
metadata:
  name:  carrentalsystem-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app:  carrentalsystem-app

  ports:
    - name:  name-of-the-port
      port:  8084
      targetPort:  9090