apiVersion: v1
kind: Pod
metadata:
  name: commentapp
  labels:
    name: comment-app
  annotations:
    owner: "Burak ozer"
    type: "Backend Service"
    create: "13.10.2022"
    email: "burakozer539@gmail.com"
spec:
  containers:
  - name: commentapp-containers
    image: musty1406/commentapp:v001
    ports:
      - containerPort: 9090
    env:
      - name: SERVERPORT
        value: "9090"

---

apiVersion: v1
kind: Pod
metadata:
  name: commentapp-group1
  labels:
    group: comment-app-dev
    takim: takim1
spec:
  containers:
  - name: commentapp-containers
    image: musty1406/commentapp:v001
    ports:
      - containerPort: 9090
    env:
      - name: SERVERPORT
        value: "9090"

---
apiVersion: v1
kind: Pod
metadata:
  name: commentapp-group2
  labels:
    group: comment-app-dev
    takim: takim2
spec:
  containers:
  - name: commentapp-containers
    image: musty1406/commentapp:v001
    ports:
      - containerPort: 9090
    env:
      - name: SERVERPORT
        value: "9090"
